preset: psr1

#enabled:
#  - "concat_with_spaces"
#  - "no_blank_lines_before_namespace"

enabled:
  - "double_arrow_multiline_whitespaces"
  - "duplicate_semicolon"
  - "elseif"
  - "empty_return"
  - "eof_ending"
  - "function_call_space"
  - "function_declaration"
  - "function_typehint_space"
  - "include"
  - "linefeed"
  - "line_after_namespace"
  - "list_commas"
  - "logical_not_operators_with_successor_space"
  - "lowercase_constants"
  - "lowercase_keywords"
  - "method_argument_space"
  - "method_separation"
  - "multiline_array_trailing_comma"
  - "multiline_spaces_before_semicolon"
  - "namespace_no_leading_whitespace"
  - "no_empty_lines_after_phpdocs"
  - "object_operator"
  - "operators_spaces"
  - "parenthesis"
  - "phpdoc_indent"
  - "phpdoc_inline_tag"
  - "phpdoc_no_access"
  - "phpdoc_no_package"
  - "phpdoc_scalar"
  - "phpdoc_short_description"
  - "phpdoc_to_comment"
  - "phpdoc_trim"
  - "phpdoc_type_to_var"
  - "phpdoc_types"
  - "phpdoc_var_without_name"
  - "remove_leading_slash_use"
  - "return"
  - "self_accessor"
  - "short_array_syntax"
  - "short_echo_tag"
  - "single_array_no_trailing_comma"
  - "single_line_after_imports"
  - "single_quote"
  - "spaces_before_semicolon"
  - "spaces_cast"
  - "standardize_not_equal"
  - "ternary_spaces"
  - "trailing_spaces"
  - "trim_array_spaces"
  - "unalign_equals"
  - "unary_operators_spaces"
  - "unused_use"
  - "visibility"

#disabled:
#  - "blankline_after_open_tag"
#  - "concat_without_spaces"
#  - "no_blank_lines_after_class_opening"
#  - "remove_lines_between_uses"
#  - "single_blank_line_before_namespace"
#  - "whitespacy_lines"

finder:
  exclude:
    - ".phpspec"
    - "spec"
    - "tests"
